language: c
sudo: true

script:
- |
  sudo add-apt-repository -y ppa:deadsnakes/ppa
  sudo apt-get update
  sudo apt-get install fuse appstream appstream-util git jq make gcc patch unzip \
  gnutls-dev libncurses-dev libgtk-3-dev libxpm-dev libjpeg-dev \
  libgif-dev libtiff5-dev libmailutils-dev libgpm-dev liblcms2-dev imagemagick \
  libmagickwand-dev libjansson-dev libotf-dev python3.6 python3.6-dev python3.7 libpython3.7-dev
- BUILD_SRC=$(pwd)
# external downloads
- wget https://github.com/probonopd/uploadtool/raw/master/upload.sh; chmod +x upload.sh
- wget https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage; mv linuxdeployqt* linuxdeployqt; chmod +x linuxdeployqt
- wget https://ftp.gnu.org/gnu/emacs/emacs-27.1.tar.gz
- wget https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/exec-x86_64.so
- wget https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/AppRun-patched-x86_64
# Unpacking
- tar xzf emacs-27.1.tar.gz
- ls -l
- mv emacs-27.1 emacs
# Building Emacs
- mkdir AppDir
- APPDIR="${BUILD_SRC}/AppDir"
- mkdir "${APPDIR}/usr"
- sudo ldconfig /usr/lib /usr/lib/python3.6
- cd emacs
- ./configure --with-x --with-x-toolkit=gtk3 --with-mailutils --with-imagemagick --with-cairo --disable-build-details --prefix="" --exec-prefix=""
- make install DESTDIR="${APPDIR}"
- cd "${BUILD_SRC}"
- rm -rf emacs
# Preparing AppDir
- cd "${BUILD_SRC}"
- cp emacs.svg "${APPDIR}"
- cp emacs.png "${APPDIR}"
#- cp emacs.desktop "${APPDIR}"
# Building
- |
  ./linuxdeployqt "${BUILD_SRC}/emacs.desktop" \
  -updateinformation="gh-releases-zsync|zilti|emacs.AppImage|continuous|Emacs*.AppImage.zsync" \
  -appimage
- bash upload.sh ./*.AppImage*
