language: c
sudo: true

script:
- |
  sudo add-apt-repository -y ppa:deadsnakes/ppa
  sudo apt-get update
  sudo apt-get install fuse appstream appstream-util git jq make gcc patch unzip \
  gnutls-dev libncurses-dev libgtk-3-dev libxpm-dev libjpeg-dev \
  libgif-dev libtiff5-dev libmailutils-dev libgpm-dev liblcms2-dev imagemagick \
  libmagickwand-dev libjansson-dev libotf-dev python3.6 libpython3.6-dev
- BUILD_SRC=$(pwd)
# external downloads
- wget https://github.com/probonopd/uploadtool/raw/master/upload.sh; chmod +x upload.sh
- wget https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage; mv linuxdeployqt* linuxdeployqt; chmod +x linuxdeployqt
- wget https://ftp.gnu.org/gnu/emacs/emacs-27.1.tar.gz
- wget https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/exec-x86_64.so
- wget https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/AppRun-patched-x86_64
# Unpacking
- tar xzf emacs-*.tar.gz
- ls -l
- mv emacs-27.1 emacs
# Building Emacs
- mkdir AppDir
- APPDIR="${BUILD_SRC}/AppDir"
- ldconfig /usr/lib /usr/lib/python3.6
- cd emacs
- ./configure --with-x --with-x-toolkit=gtk3 --with-mailutils --with-imagemagick --with-cairo --prefix="/opt" --exec-prefix="/opt" --libexecdir="/opt/libexec" --datarootdir="/opt/share" --sysconfdir="/opt/etc" --disable-build-details
- make install
- cp -r /opt "${APPDIR}/opt"
- sudo rm -rf /opt
# Preparing AppDir
- cd "${BUILD_SRC}"
- mkdir "${APPDIR}/usr"
- cp emacs.svg "${APPDIR}"
- cp emacs.png "${APPDIR}"
- cp emacs.desktop "${APPDIR}"
# Building
- |
  ./linuxdeployqt "${APPDIR}/emacs.desktop" \
  -updateinformation="gh-releases-zsync|zilti|emacs.AppImage|continuous|Emacs*.AppImage.zsync" \
  -appimage
- bash upload.sh ./*.AppImage*
